name: Publish Afika Website

on:
  push:
    branches:
      - master

jobs:
  publish-website:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - run: |
        az storage blob upload-batch -s public -d \$web --account-name afika --content-type 'text/html; charset=utf-8'