name: Publish Afika Website

on:
  push:
    branches:
      - master

jobs:
  build-and-publish-website:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: '11.x'

    - run: |
        npm install
        npm run deploy
        npm run prepare-public

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - run: |
        az storage blob upload-batch -s public -d \$web --account-name afika
